// All UI strings and copy for the application
// Centralizing strings makes it easy to update copy and potentially add i18n later

export const STRINGS = {
  // Brand
  brand: {
    name: 'Showly',
    tagline: 'Property Showing Scheduling Made Simple',
    description: 'Schedule property showings without the back-and-forth. No app downloads required.',
  },

  // Authentication
  auth: {
    login: {
      title: 'Sign in to your account',
      emailLabel: 'Email address',
      emailPlaceholder: 'agent@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      submitButton: 'Sign in',
      submittingButton: 'Signing in...',
      createAccountPrompt: 'Or',
      createAccountLink: 'create a new account',
      forgotPasswordLink: 'Forgot password?',
    },
    signup: {
      title: 'Create your account',
      nameLabel: 'Full Name',
      namePlaceholder: 'John Doe',
      emailLabel: 'Email address',
      emailPlaceholder: 'agent@example.com',
      phoneLabel: 'Phone Number',
      phonePlaceholder: '+1 (555) 123-4567',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      passwordHint: 'Must be at least 6 characters',
      confirmPasswordLabel: 'Confirm Password',
      confirmPasswordPlaceholder: '••••••••',
      submitButton: 'Create account',
      submittingButton: 'Creating account...',
      signInPrompt: 'Already have an account?',
      signInLink: 'Sign in',
      termsText: 'By signing up, you agree to our Terms of Service and Privacy Policy',
    },
    errors: {
      passwordMismatch: 'Passwords do not match',
      passwordTooShort: 'Password must be at least 6 characters',
      signInFailed: 'Failed to sign in. Please check your credentials.',
      signUpFailed: 'Failed to create account. Please try again.',
      generic: 'An error occurred. Please try again.',
    },
  },

  // Dashboard
  dashboard: {
    title: 'Dashboard',
    welcomeMessage: 'Welcome back',
    subtitle: 'Manage your properties and showings from one place',
    overview: 'Overview',
    properties: 'Properties',
    showings: 'Showings',
    settings: 'Settings',
    profile: 'Edit Profile',
    billing: 'Billing',
    signOut: 'Sign out',
    stats: {
      activeProperties: 'Active Properties',
      upcomingShowings: 'Upcoming Showings',
      thisMonth: 'This Month',
    },
    quickActions: {
      title: 'Quick Actions',
      addPropertyDescription: 'Create a new property listing and get your booking link',
      viewPropertiesDescription: 'View and manage all your property listings',
    },
    gettingStarted: {
      title: 'Getting Started',
      step1: 'Create your first property listing',
      step2: 'Share the booking link with clients',
      step3: 'Clients book showings instantly',
      step4: 'Get automatic email/SMS confirmations',
    },
  },

  // Profile
  profile: {
    title: 'Edit Profile',
    subtitle: 'Update your profile information and photo',
    nameLabel: 'Full Name',
    namePlaceholder: 'John Doe',
    emailLabel: 'Email Address',
    emailPlaceholder: 'agent@example.com',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '+1 (555) 123-4567',
    brokerageLabel: 'Brokerage (Optional)',
    brokeragePlaceholder: 'ABC Realty',
    bioLabel: 'Bio (Optional)',
    bioPlaceholder: 'Tell clients a bit about yourself and your experience...',
    photoLabel: 'Profile Picture',
    photoHint: 'This photo will appear on your booking pages',
    uploadPhoto: 'Upload Photo',
    changePhoto: 'Change Photo',
    removePhoto: 'Remove Photo',
    uploading: 'Uploading...',
    saveButton: 'Save Changes',
    savingButton: 'Saving...',
    successMessage: 'Profile updated successfully!',
    errorMessage: 'Failed to update profile. Please try again.',
    cropDialog: {
      title: 'Adjust Photo',
      description: 'Drag to reposition, use slider to zoom',
      zoomLabel: 'Zoom',
      cancelButton: 'Cancel',
      applyButton: 'Apply',
    },
  },

  // Properties
  properties: {
    title: 'Properties',
    subtitle: 'Manage your property listings and booking links',
    addNew: 'Add Property',
    edit: 'Edit',
    noProperties: 'No properties yet',
    createFirst: 'Create your first property to start scheduling showings',
    form: {
      title: 'Add New Property',
      editTitle: 'Edit Property',
      addressLabel: 'Street Address',
      addressPlaceholder: '123 Main St',
      cityLabel: 'City',
      cityPlaceholder: 'San Francisco',
      stateLabel: 'State',
      statePlaceholder: 'CA',
      zipLabel: 'ZIP Code',
      zipPlaceholder: '94102',
      priceLabel: 'Price',
      pricePlaceholder: '850000',
      bedroomsLabel: 'Bedrooms',
      bathroomsLabel: 'Bathrooms',
      sqftLabel: 'Square Feet',
      sqftPlaceholder: '2000',
      mlsLabel: 'MLS Number',
      mlsPlaceholder: 'MLS123456',
      photoLabel: 'Property Photos',
      photoPlaceholder: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994',
      photoUploadLabel: 'Upload Photos',
      photoUploadButton: 'Add Photos',
      photoUploading: 'Uploading...',
      photoRemove: 'Remove',
      photoOrUrl: 'Or enter a URL:',
      photoMoveUp: '↑',
      photoMoveDown: '↓',
      photoSetPrimary: 'Set as Primary',
      photoPrimary: 'Primary Photo',
      photoCount: (count: number) => `${count} photo${count === 1 ? '' : 's'}`,
      submitButton: 'Create Property',
      updateButton: 'Update Property',
      submittingButton: 'Creating...',
      updatingButton: 'Updating...',
      cancelButton: 'Cancel',
    },
  },

  // Bookings
  bookings: {
    title: 'Book a Showing',
    selectTime: 'Select a time',
    selectTimeSlot: 'Choose your preferred showing time',
    noTimesAvailable: 'No available times for this date',
    availableTimesTitle: 'Available Times',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    showingsScheduled: (count: number) => `${count} showing${count === 1 ? '' : 's'} scheduled this week`,
    clientInfo: 'Your Information',
    nameLabel: 'Full Name',
    namePlaceholder: 'Jane Smith',
    emailLabel: 'Email',
    emailPlaceholder: 'jane@example.com',
    phoneLabel: 'Phone',
    phonePlaceholder: '+1 (555) 123-4567',
    notesLabel: 'Questions or Notes',
    notesPlaceholder: 'Any questions about the property?',
    preApprovedLabel: 'I am pre-approved for a mortgage',
    remindersLabel: 'Send me email reminders before the showing',
    remindersHint: 'We\'ll send you reminders 24 hours and 1 hour before your showing',
    smsLabel: 'Also send me text (SMS) reminders',
    smsHint: 'Get instant confirmation and 1-hour reminder via text message. Standard messaging rates may apply.',
    smsDisclaimer: 'By checking this box, you consent to receive automated text messages about your showing. You can opt out anytime.',
    submitButton: 'Book Showing',
    submittingButton: 'Booking...',
    confirmationTitle: 'Showing Booked!',
    confirmationMessage: 'You will receive a confirmation email shortly.',
    propertyDetails: 'Property Details',
    scheduledBy: 'Scheduled by',
    contactAgent: 'Contact Agent',
    callAgent: 'Call',
    emailAgent: 'Email',
    notFound: 'Property Not Found',
    notFoundDescription: 'This property listing could not be found or is no longer available.',
    loadingProperty: 'Loading property details...',
  },

  // Settings
  settings: {
    title: 'Settings',
    subtitle: 'Manage your profile and preferences',
    profile: 'Profile',
    workingHours: 'Working Hours',
    notifications: 'Notifications',
    billing: 'Billing',
    save: 'Save Changes',
    saving: 'Saving...',
    saved: 'Changes saved successfully!',
    error: 'Failed to save settings. Please try again.',
    comingSoon: 'Settings Coming Soon',
    comingSoonDescription: 'Configure your working hours, notifications, and more',

    // Working Hours Section
    workingHoursTitle: 'Working Hours',
    workingHoursDescription: 'Set your availability for property showings',
    dayEnabled: 'Available',
    dayDisabled: 'Unavailable',
    startTime: 'Start Time',
    endTime: 'End Time',
    days: {
      monday: 'Monday',
      tuesday: 'Tuesday',
      wednesday: 'Wednesday',
      thursday: 'Thursday',
      friday: 'Friday',
      saturday: 'Saturday',
      sunday: 'Sunday',
    },

    // Showing Duration Section
    showingDurationTitle: 'Default Showing Duration',
    showingDurationDescription: 'How long each showing will last',
    durationOptions: {
      15: '15 minutes',
      30: '30 minutes',
      45: '45 minutes',
      60: '60 minutes',
    },
    customDuration: 'Custom',
    customDurationPlaceholder: 'Enter minutes',

    // Buffer Time Section
    bufferTimeTitle: 'Buffer Time Between Showings',
    bufferTimeDescription: 'Time between showings for travel and preparation',
    bufferOptions: {
      0: 'No buffer',
      15: '15 minutes',
      30: '30 minutes',
    },
    customBuffer: 'Custom',
    customBufferPlaceholder: 'Enter minutes',

    // Booking Window Section
    bookingWindowTitle: 'Booking Window',
    bookingWindowDescription: 'How far in advance clients can book showings',
    windowOptions: {
      7: '1 week',
      14: '2 weeks',
      30: '1 month',
      60: '2 months',
      90: '3 months',
    },

    // Email Branding Section
    emailBrandingTitle: 'Email Branding',
    emailBrandingDescription: 'Customize how your confirmation emails look',
    brandLogoLabel: 'Brand Logo',
    brandLogoHint: 'This logo will appear in your confirmation emails',
    uploadLogo: 'Upload Logo',
    changeLogo: 'Change Logo',
    removeLogo: 'Remove Logo',
    primaryColorLabel: 'Primary Color',
    primaryColorHint: 'Used for email headers and buttons',
    accentColorLabel: 'Accent Color',
    accentColorHint: 'Used for highlights and links',
    footerTextLabel: 'Custom Footer Text',
    footerTextPlaceholder: 'Add custom text to appear at the bottom of your emails...',
    footerTextHint: 'Optional text to include at the end of confirmation emails',
    previewEmailButton: 'Preview Email',
    resetToDefaults: 'Reset to Defaults',
  },

  // Showings
  showings: {
    title: 'Showings',
    subtitle: 'View and manage your scheduled showings',
    noShowings: 'No Showings Yet',
    noShowingsDescription: 'Showings will appear here once clients book through your property links',
    status: {
      scheduled: 'Scheduled',
      confirmed: 'Confirmed',
      completed: 'Completed',
      cancelled: 'Cancelled',
      noShow: 'No Show',
    },
    filterAll: 'All',
    filterUpcoming: 'Upcoming',
    filterPast: 'Past',
    client: 'Client',
    property: 'Property',
    date: 'Date',
    time: 'Time',
    sortBy: 'Sort by:',
    contactClient: 'Contact Client',
    viewProperty: 'View Property',
    actions: {
      confirm: '✓ Confirm',
      complete: '✓ Complete',
      cancel: '✕ Cancel',
      noShow: 'No Show',
      reschedule: 'Reschedule',
      updating: 'Updating...',
      cancelConfirm: 'Are you sure you want to cancel this showing?',
    },
    reschedule: {
      title: 'Reschedule Showing',
      selectNewTime: 'Select a new time for this showing',
      currentTime: 'Current Time',
      newTime: 'New Time',
      confirmButton: 'Reschedule Showing',
      cancelButton: 'Cancel',
      noAvailableTimes: 'No available times found. Please try a different date range.',
      success: 'Showing rescheduled successfully!',
      error: 'Failed to reschedule showing. Please try again.',
    },
  },

  // Pricing & Subscription
  pricing: {
    title: 'Choose Your Plan',
    subtitle: 'Start with a 14-day free trial. No credit card required.',
    trialBadge: 'Free Trial',
    founderBadge: 'Founder Pricing',
    founder: {
      name: 'Founder Plan',
      price: '$29',
      period: '/month',
      description: 'Lock in founder pricing forever (first 200 customers)',
      features: [
        'Unlimited property listings',
        'Unlimited showings',
        'Email notifications',
        'Custom branding',
        'Automated reminders',
        'Calendar sync',
        'Priority support',
      ],
      cta: 'Start Free Trial',
      badge: 'Limited Spots',
    },
    standard: {
      name: 'Pro Plan',
      price: '$39',
      period: '/month',
      description: 'Full access to all Showly features',
      features: [
        'Unlimited property listings',
        'Unlimited showings',
        'Email notifications',
        'Custom branding',
        'Automated reminders',
        'Calendar sync',
        'Standard support',
      ],
      cta: 'Start Free Trial',
    },
    trial: {
      title: 'Free Trial',
      duration: '14 days',
      showingLimit: '3 showings',
      description: 'Try Showly free for 14 days or 3 showings, whichever comes first',
      noCreditCard: 'No credit card required',
    },
    upgrade: {
      title: 'Upgrade to Pro',
      trialExpired: 'Your trial has ended',
      trialExpiredMessage: 'Upgrade now to continue using Showly and keep booking showings',
      selectPlan: 'Select a plan to continue',
      upgradeButton: 'Upgrade Now',
      remainingDays: (days: number) => `${days} day${days === 1 ? '' : 's'} left in trial`,
      remainingShowings: (count: number) => `${count} showing${count === 1 ? '' : 's'} left in trial`,
    },
  },

  // Billing & Subscription
  billing: {
    title: 'Billing & Subscription',
    subtitle: 'Manage your subscription and billing information',
    currentPlan: 'Current Plan',
    billingCycle: 'Billing Cycle',
    monthly: 'Monthly',
    annual: 'Annual',
    nextBilling: 'Next Billing Date',
    cancelSubscription: 'Cancel Subscription',
    cancelConfirm: 'Are you sure you want to cancel your subscription?',
    cancelButton: 'Yes, Cancel Subscription',
    manageBilling: 'Manage Billing',
    updatePayment: 'Update Payment Method',
    viewInvoices: 'View Invoices',
    reactivate: 'Reactivate Subscription',
    status: {
      active: 'Active',
      trial: 'Free Trial',
      pastDue: 'Payment Past Due',
      past_due: 'Payment Past Due', // snake_case alias for database compatibility
      cancelled: 'Cancelled',
      inactive: 'Inactive',
    } as Record<string, string>,
  },

  // Landing Page
  landing: {
    hero: {
      headline: 'Property Showing Scheduling Made Simple',
      subheadline: 'Stop the back-and-forth. Let clients book property showings instantly with your shareable link.',
      cta: 'Start Free Trial',
      secondaryCta: 'See How It Works',
      trustBadge: '14-day free trial • No credit card required',
    },
    howItWorks: {
      title: 'How It Works',
      subtitle: 'Get your first showing link in under 60 seconds',
      step1: {
        title: 'Create Your Link',
        description: 'Add your property details and get a shareable booking link instantly',
      },
      step2: {
        title: 'Share With Clients',
        description: 'Send the link via text, email, or social media. No app download required.',
      },
      step3: {
        title: 'Get Booked',
        description: 'Clients pick their time. You both get instant confirmation via email.',
      },
    },
    features: {
      title: 'Built for Real Estate Agents',
      subtitle: 'Everything you need to streamline your showings',
      feature1: {
        title: 'Instant Booking Links',
        description: 'Create a unique link for each property in seconds. Share it anywhere.',
      },
      feature2: {
        title: 'Smart Availability',
        description: 'Set your working hours once. We automatically show available time slots.',
      },
      feature3: {
        title: 'Email Reminders',
        description: 'Automatic reminders 24 hours and 1 hour before each showing.',
      },
      feature4: {
        title: 'No App Required',
        description: 'Your clients book showings from their phone browser. Zero friction.',
      },
      feature5: {
        title: 'Custom Branding',
        description: 'Add your logo and colors to confirmation emails. Stay on-brand.',
      },
      feature6: {
        title: 'Calendar Sync',
        description: 'Sync with Google Calendar. All your showings in one place.',
      },
    },
    pricing: {
      title: 'Simple, Transparent Pricing',
      subtitle: 'One plan. All features. No hidden fees.',
      cta: 'Start Your Free Trial',
    },
    finalCta: {
      title: 'Ready to Streamline Your Showings?',
      subtitle: 'Start scheduling property showings in seconds',
      cta: 'Get Started Free',
      trustBadge: 'No credit card required • Cancel anytime',
    },
    footer: {
      product: 'Product',
      features: 'Features',
      pricing: 'Pricing',
      support: 'Support',
      contact: 'Contact',
      legal: 'Legal',
      terms: 'Terms of Service',
      privacy: 'Privacy Policy',
      copyright: '© 2024 Showly. All rights reserved.',
    },
  },

  // Common
  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    save: 'Save',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    allTimesIn: (timezone: string) => `All times shown in ${timezone}`,
    timezone: 'Timezone',
  },

  // Validation
  validation: {
    required: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    invalidPhone: 'Please enter a valid phone number',
    invalidUrl: 'Please enter a valid URL',
    minLength: (min: number) => `Must be at least ${min} characters`,
    maxLength: (max: number) => `Must be no more than ${max} characters`,
  },
} as const;
